
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

default:
  outputs:
    dev:
      type: redshift
      threads: 1
      host: 127.0.0.1
      port: 5439
      user: alice
      pass: pa55word
      dbname: warehouse
      schema: dbt_alice
    prod:
      type: redshift
      threads: 1
      host: 127.0.0.1
      port: 5439
      user: alice
      pass: pa55word
      dbname: warehouse
      schema: analytics
  target: dev

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: #account

      # User/password auth
      user: # --> snowflake user_name
      password: # --> snowflake password

      role: SYSADMIN
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: dbt_cli_schema
      client_session_keep_alive: False
      
my_cloud_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ht69491.ap-south-1

      # User/password auth
      user: makebetter2020
      password: Sriram11

      role: SYSADMIN
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: cloud_schema
      client_session_keep_alive: False
